### ISSUE TITLE
Drop the consensus and resync when the node receives a significant amount of valid Agreement messages for future rounds

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1151]
In the agreement step, if we collect a significant amount of valid agreements for future rounds, it would be more convenient to trigger a synch-up procedure since it is likely that the node fell behind. This is recorded in the following `TODO`: https://github.com/dusk-network/dusk-blockchain/blob/8e8a5ab3e24b1b71b61ed50543bac6d2b6cb64c7/pkg/core/consensus/agreement/step.go#L110

**Comment by goshawk-3** [comment]
To recap meeting notes:

In order to make a decision to drop the consensus loop, a node could 

- rely on future Agreement messages. To make an attempt to verify a future Agreement, a node needs to `predict` state of Provisioners for future round based on `StakeGracePeriod`  and the known state of Provisioners (Stake, Expiry) . If valid, it does drop the consensus loop and start syncing.

- rely on `topics.Block wire message`. A node is allowed to drop the consensus loop if it is in `OutSync` mode and does receive a fully valid next block.
(ref https://github.com/dusk-network/dusk-blockchain/pull/1147#issuecomment-901904743)

**Comment by goshawk-3** [comment]
point-2 will be addressed with #1154

**Comment by toghrulmaharramov** [comment]
@autholykos Possible if within the same epoch + probably the adjacent epoch (assuming that we remove sharding) since the validator set doesn't change throughout the epoch. This is only applicable to Agreement messages and under the assumption that these messages include aggregated witnesses for the Reduction steps of the same round (which should be the case either way), otherwise the security would drop to 2^35-ish.

**Comment by autholykos** [comment]
With the latest changes to the consensus, and the short-circuiting of the `AggrAgreement`, there is a case for shelving this issue altogether
