### ISSUE TITLE
Adapt to the new and improved reward strategy

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1320]
### What is this for
This is a followup after dusk-network/rusk#614

**Comment by ureeves** [comment]
The payload of the coinbase, in the context of this change, will be:

https://github.com/dusk-network/rusk/blob/cd3431e98d3595d68277e2f38ab9ebf3ed866a9d/rusk/src/lib/transaction.rs#L69-L72

**Comment by herr-seppia** [comment]
@ureeves

I know we discussed these change together, but a question just raise in my mind:
How can the explorer show information about the block reward without derive them using txs fees and block height?

**Comment by ureeves** [comment]
In my view this **should** be computed from the transaction fees and the block height. If we don't want to use those - and I would ask why not - we could have Rusk return said information to the consensus program. Maybe some additional information in the return of a state transition?

**Comment by herr-seppia** [comment]
It's just a matter of making infos explicitly available in the block.
If we want to go for derive them, we don't need to change anything in the block header (Generator and blockheight are already there)

Btw including those info in the header and as return of EST&co should enforce checks by dusk-blockchain during the block acceptance (I'm saying "enforce" because everything is implicitly checked by the statehash match)
