### ISSUE TITLE
Restarting actively-staking Provisioners won't recover consensus

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1321]
**Describe the bug**
When the genesis Provisioner restarts, it is incapable of keeping up with the consensus. We need to check whether this affects also the Provisioners in a multi-staking scenario 

**To Reproduce**
Stop/restart the genesis Provisioner

**Expected behaviour**
The consensus should keep accepting blocks

**Logs/Screenshot**
TBD

**Comment by goshawk-3** [comment]
As per findings and tests performed there is not issue with syncing up procedure for provisioner/non-provisioner node.

root cause: Due to ~1s Consensus time  sometimes it could happen a race condition in which Provisioner node is terminated  a few milliseconds before it completes the procedure of accepting next valid block.  In a single-provisioner network, this will result into an inconsistency issue and consensus gets halted.

Example networks state:

9500{"data":{"blocks":[{"header"**:{"height":31}}]}}**
9501{"data":{"blocks":[{"header":{"height":32}}]}}
9502{"data":{"blocks":[{"header":{"height":32}}]}}
9503{"data":{"blocks":[{"header":{"height":32}}]}}
9504{"data":{"blocks":[{"header":{"height":32}}]}}
