### ISSUE TITLE
Handle the rejected transactions after a EST

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#1381]
**This issue is a followup of dusk-network/rusk#705**

_Originally posted by @herr-seppia in https://github.com/dusk-network/rusk/pull/705#pullrequestreview-951806041_

**Comment by herr-seppia** [comment]
Any transaction "rejected" is invalid (this means that rusk won't execute due to the impossibility to charge the costs).
One example is having a tx using an already spent nullifier.

To properly remove those from the mempool, a check should done during accept/finalize.
Dusk-blockchain shall remove any pending tx in the mempool that is using a nullifier already used by the txs accepted
