### ISSUE TITLE
Replace the bytes.Buffer based message passing for the empty interface{}, coupled with type assertions

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#237]
As a benchmark shows, when passing messages using the `bytes.Buffer` and encoding/decoding the data, we lose quite a bit of time.

```
goos: linux
goarch: amd64
pkg: github.com/dusk-network/dusk-blockchain/pkg/core/marshalling
BenchmarkEncodeDecodeBlock-8           3         347057829 ns/op
BenchmarkTypeCastBlock-8        84495676                14.0 ns/op
PASS
```

Thus, substituting the internal encoding/decoding of messages for a simple `interface{}` with a type assertion might increase our performance drastically.

**Comment by autholykos** [comment]
The problem of replacing the `bytes.Buffer` with an `interface{}` is that it introduces incompatibilities between `Event`s coming from the network and those propagated internally. The problem is particularly evident in the `multicaster`, where topics get prepended to the serialized message buffer, and a single default `Subscriber` listens to both internal and external messages seamlessly,  

The quickest way to solve this duality would be to pass `bytes.Buffer` alongside other types and rely on type switching on the `Subscriber`. I have the feeling that any other solution, such as adding a method on the `EventBus` that would deal with `interface{}` specifically, or creating an ad-hoc `Serializable` interface, would lead to significant duplication of login by the `multicaster` users (_in primis_ the `Coordinator`).
