### ISSUE TITLE
Modify Transactor to use rusk RPC where appropriate

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#411]
Transactor is a thin layer that reroute (cli- web-)wallet requests toward the appropriate endpoint. This issue is about phasing out the `wallet.Wallet` (reliant on UTXO and bulletproofs) and use rusk GRPC services instead (which use PLONK, phoenix transaction model and smart-contracts). In particular, this means: 
- remove dependency on `data/wallet`
- remove the decoy creation/handling (since they are specific to ringsignature)
- consider fetching inputs directly from rusk

**Comment by julesdesmit** [comment]
@devtomnl  

## Transactor commands, and what they should do

We can leave wallet DB stuff unimplemented for now, as it might take quite some work to get the DB itself adjusted to work with Phoenix as well. I'm just leaving them here for reference

### GetTxHistory

- Retrieve the transaction records from the database. Sort them based on date, and return the most recent 10.

### CreateWallet

- Make a call to Rusk, method `GenerateSecretKey`. It takes some bytes as a seed, but this can be randomly generated in the function itself.
- Once the secret key is received, the Transactor should set it on its struct.
- The secret key needs to be stored on disk, in an encrypted file. In the past, we had an AES-encrypted wallet.dat file which needed a password to decrypt.
- Make another call to rusk, method `Keys`. This returns the view key and public key.
- Return the public key.

### LoadWallet

- Should attempt to decrypt the on-disk file. On success, sets the private key on the transactor struct.
- Make a call to rusk, method `Keys`. Return the public key.

### CreateFromSeed

- Same as CreateWallet, but the seed can be passed as an argument.

### ClearWalletDatabase

- Removes the on-disk wallet database.

### CallContract

- If private key is set, fetch inputs from the wallet db until we have enough to cover the transaction (amount inputted >= amount to send).
- Make a call to rusk, method `NewTransaction`. (NOTE: `NewTransaction` currently does not yet support adding calldata to transactions. You can leave a TODO there for now.)
- Send the received transaction to the node's mempool (this can go over the event bus, or the rpc bus).
- Return the tx hash.

### Transfer

- If private key is set, fetch inputs from the wallet db until we have enough to cover the transaction (amount inputted >= amount to send).
- Make a call to rusk, method `NewTransaction`.
- Send the received transaction to the node's mempool (this can go over the event bus, or the rpc bus).
- Return the tx hash.

### Bid

- If private key is set, fetch inputs from the wallet db until we have enough to cover the transaction (amount inputted >= amount to send).
- Make an internal call to the block generator, to retrieve the blind bid `M` value. (Scalar)
- Make a call to rusk, method `NewTransaction`. (NOTE: `NewTransaction` does not yet currently support adding any peripheral data to transactions. You can leave a TODO there for now.)
- Send the received transaction to the node's mempool (this can go over the event bus, or the rpc bus).
- Return the tx hash.

### Stake

- If private key is set, fetch inputs from the wallet db until we have enough to cover the transaction (amount inputted >= amount to send).
- Make an internal call to the consensus, to retrieve the provisioner BLS key.
- Make a call to rusk, method `NewTransaction`. (NOTE: `NewTransaction` does not yet currently support adding any peripheral data to transactions. You can leave a TODO there for now.)
- Send the received transaction to the node's mempool (this can go over the event bus, or the rpc bus).
- Return the tx hash.

### GetWalletStatus

- Returns whether or not the private key is set on the Transactor.

### GetAddress

- If the private key is set, make a call to rusk, method `Keys`. Return the public key.

### GetBalance

- Go through the wallet database, counting up all of the values of the different inputs. Return the sum.

## To be implemented

There needs to be some kind of mechanism to receive newly unspent outputs for a specific private key, so that the wallet db can be updated accordingly, saving us the hassle of having to do a full scan every time.

This can be deferred to a different issue.

**Comment by julesdesmit** [comment]
Fixed via #450
