### ISSUE TITLE
Implement some type of session management functionality for the wallet

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#509]
For security reasons, it would be wise to have session-based availability of the wallet keys. For instance, we can add a gRPC method that unloads the keys and essentially locks up the wallet again, which can be called by front-end apps in order to secure funds after a timeout. 

Another approach could be to not keep the keys inside of a wallet struct, but instead requiring a password every time a user wishes to do a key-based operation, which then decrypts the keys, performs the operation, and then drops them after they go out of scope.

**Comment by autholykos** [comment]
After speaking with @Fulviuus, the best approach would look like a JWT session token with renewable expiry set at 2-3 minutes to inject into all GRPC calls but the status and the login ones (`CreateWallet` - `LoadWallet`). RUSK does not need session propagation since the `Secret Key` is communicated at every call.

**Comment by autholykos** [comment]
Closed via #560
