### ISSUE TITLE
Test that in TestHarness spawned networks GetCandidate does not hit the peers but it is satisfied by local cache

### ISSUE THREAD

**Issue by autholykos** [dusk-network/dusk-blockchain#629]
`CandidateBroker` maintain a cache of Candidates propagated through the network. For a small network, candidates should organically receive all propagated blocks all the time. Therefore, if the `CandidateBroker` does not have within its cache a candidate block, this points to a different, non-network, related problem with Block propagation/collection

**Comment by ggoranov** [comment]
`Test scenario:` 9 nodes with 9 bidders test-harness network run on a single host

`Prerequisites`:
- Disable fetch-from-peers for GetCandidate call
- Disable filtering by ValidHash event

By applying the prerequisites above, each node Candidate Storage never loses (purges) the winning Candidate. 

`Observed result`: Stable consensus without any `candidate-not-found` error reported. Harness manually terminated after almost 80K rounds.

GraphQL query response from node 0:
```json
{
   "data":{
      "blocks":[
         {
            "header":{
               "height":77776,
               "timestamp":"2020-08-20 10:10:02"
            }
         }
      ]
   }
}
```

`Conclusion: ` The observation indicates that `GetCandidate` fails only after nodes losing (purging) the winning Candidate due to not marked with `topics.ValidCandidateHash` message
