### ISSUE TITLE
After start & stop a Dusk node, when attempting to restart, node reports (fail missing coinbase tx)

### ISSUE THREAD

**Issue by devtomnl** [dusk-network/dusk-blockchain#753]
```
{"app":"dusk","level":"panic","msg":"missing coinbase tx","prefix":"main","time":"2020-11-10T09:57:25+01:00"}
{"app":"dusk","error":"\u0026{Logger:0xc000152930 Data:map[app:dusk prefix:main] Time:2020-11-10 09:57:25.171204353 +0100 CET m=+0.019848977 Level:panic Caller:\u003cnil\u003e Message:missing coinbase tx Buffer:\u003cnil\u003e Context:\u003cnil\u003e err:}","level":"error","msg":"Application panic","prefix":"main","time":"2020-11-10T09:57:25+01:00"}
```

The issue is mitigated by forcing a cleanup of the chain data:
`rm -rf /opt/dusk/dusk_data/chain/*`

**Comment by julesdesmit** [comment]
With the current setup, this happens because the legacy genesis block has a bid/stake transaction at the end. When first starting the node (when it has no chain data), the transactions are not checked, thus this error only appears after stopping and restarting (and most likely will only happen if we stop and restart on genesis).

**Comment by julesdesmit** [comment]
This should be mitigated if nodes are at least one block past genesis, but to really fix this issue, the genesis block will need to be fully re-generated and new wallets need to be made.
