### ISSUE TITLE
Implement ping loop between peers

### ISSUE THREAD

**Issue by julesdesmit** [dusk-network/dusk-blockchain#89]
As it stands right now, the idle time for a peer is set to one minute. This can create some issues, as the consensus step timer can greatly exceed that amount of time if it fails to converge on a block a few times. If there is nothing else going on in the network, it means that nodes will timeout with each other after the 4th failed attempt (as the step timer is then set to 80 seconds).

My first instinct was to increase the timeout to the maximum consensus step time (5120 seconds), but implementing a ping loop that probes a node every 30 seconds or so seems more elegant.

**Comment by CPerezz** [comment]
I reviewed the Kademlia paper to see if they have any suggestions about the time to query other peers. And they don't.

But why instead of making `PING` we don't do something similar to `FIND_NODE` and if it does not return any peers (timeout), then we PING just to make sure that the peer is down and then we delete it from our buckets.
